//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace docbox.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dx_department
    {
        public dx_department()
        {
            this.dx_userdept = new HashSet<dx_userdept>();
        }
    
        public int deptid { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<dx_userdept> dx_userdept { get; set; }
    }
}
