//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace docbox.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dx_fileversion
    {
        public long fileid { get; set; }
        public long versionid { get; set; }
        public int versionnumber { get; set; }
        public System.DateTime updatedate { get; set; }
        public string description { get; set; }
        public int size { get; set; }
        public string updatedby { get; set; }
    
        public virtual dx_files dx_files { get; set; }
        public virtual dx_user dx_user { get; set; }
    }
}
