//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace docbox.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dx_files
    {
        public dx_files()
        {
            this.dx_fileversion = new HashSet<dx_fileversion>();
            this.dx_privilege = new HashSet<dx_privilege>();
        }
    
        public long fileid { get; set; }
        public string filename { get; set; }
        public string parentpath { get; set; }
        public string ownerid { get; set; }
        public int size { get; set; }
        public byte[] isencrypted { get; set; }
        public byte[] isarchived { get; set; }
        public byte[] islocked { get; set; }
        public string type { get; set; }
        public System.DateTime creationdate { get; set; }
        public string lockedby { get; set; }
    
        public virtual ICollection<dx_fileversion> dx_fileversion { get; set; }
        public virtual ICollection<dx_privilege> dx_privilege { get; set; }
        public virtual dx_user dx_user { get; set; }
        public virtual dx_user dx_user1 { get; set; }
    }
}
