//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace docbox.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dx_user
    {
        public dx_user()
        {
            this.dx_files = new HashSet<dx_files>();
            this.dx_files1 = new HashSet<dx_files>();
            this.dx_fileversion = new HashSet<dx_fileversion>();
            this.dx_privilege = new HashSet<dx_privilege>();
            this.dx_userdept = new HashSet<dx_userdept>();
        }
    
        public string userid { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public System.DateTime dob { get; set; }
        public string role { get; set; }
        public string pwdhash { get; set; }
        public int questionid { get; set; }
        public string phone { get; set; }
        public string anshash { get; set; }
        public string actcodehash { get; set; }
        public int accesslevel { get; set; }
        public string psalt { get; set; }
    
        public virtual ICollection<dx_files> dx_files { get; set; }
        public virtual ICollection<dx_files> dx_files1 { get; set; }
        public virtual ICollection<dx_fileversion> dx_fileversion { get; set; }
        public virtual ICollection<dx_privilege> dx_privilege { get; set; }
        public virtual ICollection<dx_userdept> dx_userdept { get; set; }
    }
}
