//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace docbox.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dxss_docboxEntities1 : DbContext
    {
        public dxss_docboxEntities1()
            : base("name=dxss_docboxEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<dx_department> dx_department { get; set; }
        public DbSet<dx_files> dx_files { get; set; }
        public DbSet<dx_fileversion> dx_fileversion { get; set; }
        public DbSet<dx_privilege> dx_privilege { get; set; }
        public DbSet<dx_user> dx_user { get; set; }
        public DbSet<dx_userdept> dx_userdept { get; set; }
    }
}
